#Para empezar tenemos que saber que la primera tarjeta de red está en DCHP, y la segunda targeta de red, tiene la ip 193.168.3.220/24
#y nombre de dominio micentro.edu. Los DNS son 1.1.1.1 y 8.8.8.8
#por lo tanto esta sería la configuración:

# Let NetworkManager manage all devices on this system
network:
  version: 2
    renderer: NetworkManager
      ethernets:
        ens18:
          dhcp4: true
        ens19:
          addresses: [193.168.3.220/24]
          nameservers:        
            search: [micentro.edu]
            addresses: [1.1.1.1, 8.8.8.8]
